# Generated by Django 3.2.5 on 2021-08-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_0', models.CharField(max_length=200)),
                ('title_1', models.CharField(max_length=200)),
            ],
        ),
    ]
